// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    var init;
    init = function(app_id, rest_key) {
      return $.parse.init(app_id, rest_key);
    };
    init('ch0uvZw2sfj9JKchnyR9KQxPsw28KKYCbgd3qCBe', '99x5k3k0JSJPYFJSThLgxfhakLirY9zvrqs6LFcs');
    $('#btn_terminar').click(function() {
      var puntaje_total;
      $.cookie('respuestas_cookie', null);
      puntaje_total = 0;
      return window.location.reload();
    });
    $('#btn_registrar').click(function() {
      var p, puntaje_total;
      if ($('#user').val() === '') {
        return alert("Debe ingresar un nombre");
      } else {
        p = {
          username: $('#user').val(),
          email: $('#mail').val(),
          puntaje: puntaje_total,
          password: '123456'
        };
        $.cookie('respuestas_cookie', null);
        puntaje_total = 0;
        return $.parse.post('users', p, function(json) {
          if (json.sessionToken !== null) {
            console.log("valor de sessionToken: " + json.sessionToken);
            alert("Datos cargados correctamente");
            return $('#btn_lista_puntajes').click();
          }
        });
      }
    });
    $('#btn_users').click(function() {
      return $.parse.get("users", function(json) {
        var results;
        results = json.results;
        return results.forEach(function(user) {
          return console.log("user: " + user.username);
        });
      });
    });
    return $('#btn_carga').click(function() {
      return $.parse.get("users", function(json) {
        var results;
        results = json.results;
        return results.forEach(function(user) {
          if (user.id_pregunta === '5') {
            console.log("cargo la pregunta con id 5");
            return console.log("id: " + user.id_pregunta + " ,contenido: " + pregunta.contenido + ", respuesta: " + pregunta.respuesta);
          }
        });
      });
    });
  });

}).call(this);
